/**
 * Demo sample data for new self-service accounts.
 * Allows instant exploration of Flux, Brief, Alerte and Statistici.
 */

import { nowISO } from "./dateUtils";

export const DEMO_CLAIMS = [
  {
    id: "demo-claim-1",
    isDemo: true,
    nrAuto: "B 101 WDA",
    marcaModel: "BMW 320d (2021)",
    numeClient: "Popescu Ion",
    telefonClient: "0722 101 202",
    asigurator: "Omniasig VIG",
    tipDosar: "RCA",
    status: "deschidere",
    observatii: "Dosar demonstrativ — Acord reparație emis.",
    sumaDeviz: 6450,
    pieseStatus: "Verificare necesar",
    dataDeschidere: nowISO(),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: "demo-claim-2",
    isDemo: true,
    nrAuto: "CJ 88 DAE",
    marcaModel: "Volkswagen Golf VIII",
    numeClient: "Ionescu Maria",
    telefonClient: "0733 888 999",
    asigurator: "Allianz-Țiriac",
    tipDosar: "CASCO",
    status: "piese_comandate",
    observatii: "Piese de schimb comandate (bara față, far stânga LED).",
    sumaDeviz: 11200,
    pieseStatus: "Sosesc pe 22 Aug",
    termenLivrarePiese: "2026-08-22",
    dataDeschidere: nowISO(),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: "demo-claim-3",
    isDemo: true,
    nrAuto: "TM 45 RPR",
    marcaModel: "Audi A4 Avant",
    numeClient: "Dumitrescu Andrei",
    telefonClient: "0744 555 666",
    asigurator: "Groupama Asigurări",
    tipDosar: "RCA",
    status: "programat",
    observatii: "Programat la tinichigerie & vopsitorie.",
    sumaDeviz: 8900,
    dataProgramare: "2026-08-20",
    programareStatus: "neonorat",
    dataDeschidere: nowISO(),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: "demo-claim-4",
    isDemo: true,
    nrAuto: "IF 12 FIX",
    marcaModel: "Mercedes-Benz CLA",
    numeClient: "Vasilescu Elena",
    telefonClient: "0755 123 456",
    asigurator: "Asirom VIG",
    tipDosar: "RCA",
    status: "in_lucru",
    observatii: "În faza de vopsire & montaj.",
    sumaDeviz: 14700,
    dataDeschidere: nowISO(),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: "demo-claim-5",
    isDemo: true,
    nrAuto: "B 777 ACC",
    marcaModel: "Skoda Octavia IV",
    numeClient: "Radu Cristian",
    telefonClient: "0766 777 888",
    asigurator: "Generali România",
    tipDosar: "CASCO",
    status: "accept_plata",
    observatii: "Reparație finalizată — Se așteaptă acceptul de plată.",
    sumaDeviz: 5300,
    dataDeschidere: nowISO(),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
